#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on 16/04/2015
Versão 1.3
@author: Lucas Igor Balthazar
"""
import sys, math
import numpy as np
import matplotlib.pyplot as plt
import time

class RK4(object):
    def __init__(self):
        pass
        
    def funcao(self,x,y,h,n):
        self.Y = np.array([])
        self.X = np.array([])
        self.K_1 = np.array([])
        self.K_2 = np.array([])
        self.K_3 = np.array([])
        self.K_4 = np.array([])
        func=lambda x,y: -x*y     # <= Função f'(x,y) a ser iterada pelo método RK4 
        
        for i in range(n):
            print(y)
            self.Y = np.append(self.Y, y)
            print(x)
            self.X = np.append(self.X, x)
            K1=func(x,y)
            print(K1)
            self.K_1 = np.append(self.K_1, K1)
            a=x+(h/2)
            b=(y+(h/2)*K1)
            K2=func(a,b)
            print(K2)
            self.K_2 = np.append(self.K_2, K2)
            c=x+(h/2)
            d=(y+(h/2)*K2)
            K3=func(c,d)
            print(K3)
            self.K_3 = np.append(self.K_3, K3)
            e=x+h
            f=(y+h*K3)
            K4=func(e,f)
            print(K4)
            self.K_4 = np.append(self.K_4, K4)
            y=y+(h/6)*(K1+2*K2+2*K3+K4)
            x += h

        # Criando arquivo de saída
        texto = 'X\tY\tK1\tK2\tK3\tK4'
        datahora = time.strftime("_%Y-%m-%d_%H-%M-%S", time.localtime())
        self.dados = np.column_stack((self.X, self.Y, self.K_1, self.K_2, self.K_3, self.K_4))
        np.savetxt('RungeKutta'+datahora+'.txt',self.dados,delimiter='\t',newline='\r\n',header = texto)
##        nomearq = 'RungeKutta'+datahora+'.txt'
##        np.savetxt(nomearq,self.dados,delimiter='\t',newline='\r\n')
##        f=open(nomearq,'r')
##        leitura = f.read().strip()
##        f.close() 
##        f=open(nomearq,'w')
##        f.write(texto+'\n')
##        f.write(leitura)
##        f.close()

        #Plotar gráfico        
        plt.plot(self.X,self.Y)
        plt.show()
        
        
a = RK4()
            
            
            

